// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using luna.Models;

#nullable disable

namespace luna.Migrations
{
    [DbContext(typeof(AsphyxiaContext))]
    [Migration("20260116145544_260116-1")]
    partial class _2601161
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("luna.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("char(16)")
                        .HasColumnName("card_id")
                        .IsFixedLength();

                    b.Property<string>("CardNo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("char(16)")
                        .HasColumnName("card_no")
                        .IsFixedLength();

                    b.Property<int>("Paseli")
                        .HasColumnType("int(11)")
                        .HasColumnName("paseli");

                    b.Property<string>("PaseliSession")
                        .HasMaxLength(16)
                        .HasColumnType("char(16)")
                        .HasColumnName("paseli_session")
                        .IsFixedLength();

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("char(4)")
                        .HasColumnName("pass")
                        .IsFixedLength();

                    b.Property<string>("RefId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("char(16)")
                        .HasColumnName("ref_id")
                        .IsFixedLength()
                        .HasComment("same with dataid");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("card", null, t =>
                        {
                            t.HasComment("Stores e-amusement cards");
                        });
                });

            modelBuilder.Entity("luna.Models.Efmigrationshistory", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("MigrationId")
                        .HasName("PRIMARY");

                    b.ToTable("__efmigrationshistory", (string)null);
                });

            modelBuilder.Entity("luna.Models.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("company_code");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("country");

                    b.Property<string>("CountryJName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("country_jname");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("country_name");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("customer_code");

                    b.Property<string>("FacilityId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("facility_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("PCBId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("pcb_id");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("region");

                    b.Property<string>("RegionJName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("region_jname");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("region_name");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasDefaultValue(0)
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("facility", null, t =>
                        {
                            t.HasComment("Stores facility");
                        });
                });

            modelBuilder.Entity("luna.Models.SvItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<uint>("ItemId")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("item_id");

                    b.Property<uint>("Param")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("param");

                    b.Property<int>("Profile")
                        .HasColumnType("int(11)")
                        .HasColumnName("profile");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Profile" }, "FK_profile_to_card(id)");

                    b.ToTable("sv_items", null, t =>
                        {
                            t.HasComment("Data store(Items) for Sound Voltex");
                        });
                });

            modelBuilder.Entity("luna.Models.SvMusic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("artist");

                    b.Property<string>("ArtistYomigana")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("artist_yomigana");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<string>("TitleYomigana")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title_yomigana");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("sv_music", null, t =>
                        {
                            t.HasComment("Data store(Music) for Sound Voltex");
                        });
                });

            modelBuilder.Entity("luna.Models.SvParam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Param")
                        .IsRequired()
                        .HasMaxLength(-1)
                        .HasColumnType("longtext")
                        .HasColumnName("param");

                    b.Property<uint>("ParamCount")
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("param_count");

                    b.Property<int>("ParamId")
                        .HasColumnType("int(11)")
                        .HasColumnName("param_id");

                    b.Property<int>("Profile")
                        .HasColumnType("int(11)")
                        .HasColumnName("profile");

                    b.Property<int>("Type")
                        .HasColumnType("int(11)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Profile" }, "FK_param_profile_to_profile(id)");

                    b.ToTable("sv_params", null, t =>
                        {
                            t.HasComment("Data store(Params) for Sound Voltex");
                        });
                });

            modelBuilder.Entity("luna.Models.SvProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ushort>("AppealId")
                        .HasColumnType("smallint(5) unsigned")
                        .HasColumnName("appeal_id");

                    b.Property<byte>("ArsOption")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasColumnName("ars_option");

                    b.Property<int>("Bgm")
                        .HasColumnType("int(11)")
                        .HasColumnName("bgm");

                    b.Property<uint>("BlasterCount")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("blaster_count");

                    b.Property<uint>("BlasterEnergy")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("blaster_energy");

                    b.Property<sbyte>("BlasterPassEnable")
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("blaster_pass_enable");

                    b.Property<ulong>("BlasterPassLimitDate")
                        .HasColumnType("bigint(20) unsigned")
                        .HasColumnName("blaster_pass_limit_date");

                    b.Property<int>("Card")
                        .HasColumnType("int(11)")
                        .HasColumnName("card");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<uint>("DayCount")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("day_count");

                    b.Property<int>("DrawAdjust")
                        .HasColumnType("int(11)")
                        .HasColumnName("draw_adjust");

                    b.Property<byte>("EarlyLateDisp")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasColumnName("early_late_disp");

                    b.Property<byte>("EffCLeft")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasColumnName("eff_c_left");

                    b.Property<byte>("EffCRight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(3) unsigned")
                        .HasColumnName("eff_c_right")
                        .HasDefaultValueSql("'1'");

                    b.Property<ushort>("ExtrackEnergy")
                        .HasColumnType("smallint(5) unsigned")
                        .HasColumnName("extrack_energy");

                    b.Property<byte>("GaugeOption")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasColumnName("gauge_option");

                    b.Property<byte>("Headphone")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasColumnName("headphone");

                    b.Property<int>("Hispeed")
                        .HasColumnType("int(11)")
                        .HasColumnName("hispeed");

                    b.Property<string>("KacId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("kac_id")
                        .HasDefaultValueSql("'VOLTEX'");

                    b.Property<uint>("Lanespeed")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("lanespeed");

                    b.Property<int>("LastMusicId")
                        .HasColumnType("int(11)")
                        .HasColumnName("last_music_id");

                    b.Property<byte>("LastMusicType")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasColumnName("last_music_type");

                    b.Property<uint>("MaxPlayChain")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("max_play_chain");

                    b.Property<uint>("MaxWeekChain")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("max_week_chain");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("name")
                        .HasDefaultValueSql("'VOLTEX'");

                    b.Property<int>("Nemsys")
                        .HasColumnType("int(11)")
                        .HasColumnName("nemsys");

                    b.Property<byte>("NotesOption")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasColumnName("notes_option");

                    b.Property<int>("Pcb")
                        .HasColumnType("int(11)")
                        .HasColumnName("pcb")
                        .HasComment("equals with block_no");

                    b.Property<uint>("PlayChain")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("play_chain");

                    b.Property<uint>("PlayCount")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("play_count");

                    b.Property<short>("SkillBaseId")
                        .HasColumnType("smallint(6)")
                        .HasColumnName("skill_base_id");

                    b.Property<short>("SkillLevel")
                        .HasColumnType("smallint(6)")
                        .HasColumnName("skill_level");

                    b.Property<short>("SkillNameId")
                        .HasColumnType("smallint(6)")
                        .HasColumnName("skill_name_id");

                    b.Property<byte>("SortType")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasColumnName("sort_type");

                    b.Property<int>("StampA")
                        .HasColumnType("int(11)")
                        .HasColumnName("stampA");

                    b.Property<int>("StampB")
                        .HasColumnType("int(11)")
                        .HasColumnName("stampB");

                    b.Property<int>("StampC")
                        .HasColumnType("int(11)")
                        .HasColumnName("stampC");

                    b.Property<int>("StampD")
                        .HasColumnType("int(11)")
                        .HasColumnName("stampD");

                    b.Property<int>("SubBg")
                        .HasColumnType("int(11)")
                        .HasColumnName("sub_bg");

                    b.Property<uint>("TodayCount")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("today_count");

                    b.Property<uint>("WeekChain")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("week_chain");

                    b.Property<uint>("WeekCount")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("week_count");

                    b.Property<uint>("WeekPlayCount")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("week_play_count");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Card" }, "card")
                        .IsUnique();

                    b.ToTable("sv_profile", null, t =>
                        {
                            t.HasComment("Data store(Profile) for Sound Voltex");
                        });
                });

            modelBuilder.Entity("luna.Models.SvScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ButtonRate")
                        .HasColumnType("int(11)")
                        .HasColumnName("buttonRate");

                    b.Property<int>("Clear")
                        .HasColumnType("int(11)")
                        .HasColumnName("clear");

                    b.Property<int>("Exscore")
                        .HasColumnType("int(11)")
                        .HasColumnName("exscore");

                    b.Property<int>("Grade")
                        .HasColumnType("int(11)")
                        .HasColumnName("grade");

                    b.Property<int>("LongRate")
                        .HasColumnType("int(11)")
                        .HasColumnName("longRate");

                    b.Property<int>("MusicId")
                        .HasColumnType("int(11)")
                        .HasColumnName("music_id");

                    b.Property<int>("Profile")
                        .HasColumnType("int(11)")
                        .HasColumnName("profile");

                    b.Property<int>("Score")
                        .HasColumnType("int(11)")
                        .HasColumnName("score");

                    b.Property<int>("Type")
                        .HasColumnType("int(11)")
                        .HasColumnName("type");

                    b.Property<int>("VolRate")
                        .HasColumnType("int(11)")
                        .HasColumnName("volRate");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MusicId" }, "FK_musicid_to_music(id)");

                    b.HasIndex(new[] { "Profile" }, "FK_profile_to_profile(id)");

                    b.ToTable("sv_scores", null, t =>
                        {
                            t.HasComment("Data store(Scores) for Sound Voltex");
                        });
                });

            modelBuilder.Entity("luna.Models.SvItem", b =>
                {
                    b.HasOne("luna.Models.SvProfile", "ProfileNavigation")
                        .WithMany("SvItems")
                        .HasForeignKey("Profile")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_profile_to_card(id)");

                    b.Navigation("ProfileNavigation");
                });

            modelBuilder.Entity("luna.Models.SvParam", b =>
                {
                    b.HasOne("luna.Models.SvProfile", "ProfileNavigation")
                        .WithMany("SvParams")
                        .HasForeignKey("Profile")
                        .IsRequired()
                        .HasConstraintName("FK_param_profile_to_profile(id)");

                    b.Navigation("ProfileNavigation");
                });

            modelBuilder.Entity("luna.Models.SvProfile", b =>
                {
                    b.HasOne("luna.Models.Card", "CardNavigation")
                        .WithOne("SvProfile")
                        .HasForeignKey("luna.Models.SvProfile", "Card")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_card_to_card(id)");

                    b.Navigation("CardNavigation");
                });

            modelBuilder.Entity("luna.Models.SvScore", b =>
                {
                    b.HasOne("luna.Models.SvMusic", "Music")
                        .WithMany("SvScores")
                        .HasForeignKey("MusicId")
                        .IsRequired()
                        .HasConstraintName("FK_musicid_to_music(id)");

                    b.HasOne("luna.Models.SvProfile", "ProfileNavigation")
                        .WithMany("SvScores")
                        .HasForeignKey("Profile")
                        .IsRequired()
                        .HasConstraintName("FK_profile_to_profile(id)");

                    b.Navigation("Music");

                    b.Navigation("ProfileNavigation");
                });

            modelBuilder.Entity("luna.Models.Card", b =>
                {
                    b.Navigation("SvProfile");
                });

            modelBuilder.Entity("luna.Models.SvMusic", b =>
                {
                    b.Navigation("SvScores");
                });

            modelBuilder.Entity("luna.Models.SvProfile", b =>
                {
                    b.Navigation("SvItems");

                    b.Navigation("SvParams");

                    b.Navigation("SvScores");
                });
#pragma warning restore 612, 618
        }
    }
}
